services:
  back-end:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: back-end
      dockerfile: Dockerfile
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgreSQL
      POSTGRES_DB: CatManga
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: